// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mafia_kz.Models;

namespace mafia_kz.Migrations
{
    [DbContext(typeof(MafiaDbContext))]
    [Migration("20190524153113_Initial1")]
    partial class Initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("mafia_kz.Models.Player", b =>
                {
                    b.Property<int>("Player_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Games_played");

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<int>("Loose_games");

                    b.Property<int>("Win_games");

                    b.Property<bool>("isAdmin");

                    b.HasKey("Player_id");

                    b.HasAlternateKey("Login");

                    b.ToTable("_players");
                });
#pragma warning restore 612, 618
        }
    }
}
